project:
  type: website
  output-dir: docs

website:
  title: "Career_Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: about.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

